# Workaround for https://github.com/quarkiverse/quarkus-groovy/issues/256
quarkus.native.additional-build-args=\
  --report-unsupported-elements-at-runtime,\
  --initialize-at-run-time=io.netty.internal.tcnative.SSL\\,\
io.netty.internal.tcnative.SSLPrivateKeyMethod\\,\
io.netty.internal.tcnative.AsyncSSLPrivateKeyMethod\\,\
io.netty.internal.tcnative.CertificateCompressionAlgo\\,\
io.netty.internal.tcnative.CertificateVerifier\\,\
io.netty.handler.ssl.ReferenceCountedOpenSslEngine\\,\
io.netty.handler.ssl.ReferenceCountedOpenSslContext\\,\
io.netty.handler.ssl.OpenSslAsyncPrivateKeyMethod\\,\
io.netty.handler.ssl.OpenSslPrivateKeyMethod
